# Site settings
title: Keller Jordan blog
email: 
description: "Interesting results of simple machine learning experiments."
baseurl: ""
url: "http://kellerjordan.github.io"
twitter_username: kellerjordan0
github_username:  KellerJordan

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
