baseURL: http://kellerjordan.github.io
languageCode: en-us
title: Keller Jordan blog
theme: "PaperMod"
params:
    homeInfoParams:
        title: Hello
        content: >
            <img style="padding-bottom:10px" src=/images/desert3.jpg>
            <div style="display: grid; grid-template-columns: auto 80px; min-height: 40px">
            <div style="margin-right: 10px; display: flex; align-items: end">
            This blog is a place for some results that I'm currently thinking about.
            </div>
            <div style="display: flex; align-items: center">
            <img style="height: 40px;" src=/images/internet.gif>
            </div>
            </div>

    socialIcons:
        - name: "github"
          url: "https://github.com/kellerjordan"
        - name: "twitter"
          url: "https://twitter.com/kellerjordan0"
menu:
    main:
        - name: About
          url: about
          weight: 5
markup:
    goldmark:
      renderer:
        unsafe: true

