baseURL: http://kellerjordan.github.io
languageCode: en-us
title: Keller Jordan blog
theme: "PaperMod"
params:
    homeInfoParams:
        title: Hello
        content: >
            <img style="padding-bottom:10px" src=/images/desert3.jpg>
            <div style="position: relative">
            <span style="position: absolute; bottom: 0; left: 0">
            This blog is a place for some results that I'm currently thinking about.
            </span>
            <span>
            <img height=28px style="float: right" src=/images/ie.gif>
            <img height=38px style="float: right; margin-right: 36px" src=/images/internet.gif>
            </span>
            </div>

    socialIcons:
        - name: "github"
          url: "https://github.com/kellerjordan"
        - name: "twitter"
          url: "https://twitter.com/kellerjordan0"
menu:
    main:
        - name: About
          url: about
          weight: 5
markup:
    goldmark:
      renderer:
        unsafe: true

